/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_gulden_framework_jjack_JJackSystem */

#ifndef _Included_de_gulden_framework_jjack_JJackSystem
#define _Included_de_gulden_framework_jjack_JJackSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef de_gulden_framework_jjack_JJackSystem_DEBUG
#define de_gulden_framework_jjack_JJackSystem_DEBUG 0L
/*
 * Class:     de_gulden_framework_jjack_JJackSystem
 * Method:    getSampleRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_gulden_framework_jjack_JJackSystem_getSampleRate
  (JNIEnv *, jclass);

/*
 * Class:     de_gulden_framework_jjack_JJackSystem
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_gulden_framework_jjack_JJackSystem_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     de_gulden_framework_jjack_JJackSystem
 * Method:    nativeStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_gulden_framework_jjack_JJackSystem_nativeStart
  (JNIEnv *, jclass);

/*
 * Class:     de_gulden_framework_jjack_JJackSystem
 * Method:    nativeDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_gulden_framework_jjack_JJackSystem_nativeDestroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
