/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sequencer.nativecode.linuxclock;

public class linuxclock {
  public static void set_ticktime_nanos(int nanos) {
    linuxclockJNI.set_ticktime_nanos(nanos);
  }

  public static void next_tick() {
    linuxclockJNI.next_tick();
  }

}
