/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sequencer.nativecode.linuxclock;

class linuxclockJNI {
  public final static native void set_ticktime_nanos(int jarg1);
  public final static native void next_tick();
}
